---
# CNN on MNIST
# model
model_type: 'cnn_hetero'
cnn_hidden_size: [64, 128, 128]

# data
dataset_type: 'CIFAR10'                    # MNIST and CIFAR10
data_shape: [3, 32, 32]
classes_size: 10
data_partition_pattern: 3
non_iid_ratio: 8

# batch size
local_batch_size: 32
test_batch_size: 32
client_test_batch_size: 32

# training setting
lr: 0.01
decay_rate: 0.993
min_lr: 0.001
momentum: 0.9
weight_decay: 0.0005

# global control
client_num: 100
active_client_num: 10
epoch_num: 600
local_iters: 50

# CUDA
server_use_cuda: True
server_cuda: '3'
client_use_cuda: True
client_cuda: '-1'

# path
dataset_path: '/data/slwang/datasets'
model_save_path: '/data/slwang/FL_PS_MPI_HeteroFL/model_save/'

# seed
model_init_seed: 2024
client_selection_seed: 2024
data_partition_seed: 2024

# algorithm paras
# algorithm parameters
model_ratio: [
    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
    0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
    0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75,
    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0
]                                         # make sure that the size of model_ratio equals client_num
norm: 'bn'
scale: True
norm_track: False
